classes/urls.py
from django.urls import path

from . import views
from .views import ClassesView, ClassesDetailView, ClassesDeleteView

app_name = 'classes'

urlpatterns = [
    path('', ClassesView.as_view(), name='list'),
    path('detail/<int:pk>', ClassesDetailView.as_view(), name='classes-detail'),
    path('delete/<int:pk>', ClassesDeleteView.as_view(), name='classes-delete'),
    path('add/', views.add, name='add'),
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

samuelsharon/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('classes/', include('classes.urls')),
]

classes/models.py
from django.db import models

# Create your models here.
class Classes(models.Model):
    matkul = models.CharField(max_length=45)
    dosen = models.CharField(max_length=75)
    sks = models.CharField(max_length=2)
    desc = models.TextField()
    semester = models.CharField(max_length=45)
    ruang = models.CharField(max_length=45)

home/models.py
from django.db import models

# Create your models here.

classes/forms.py
from django import forms

from .models import Classes

class ClassesForm(forms.ModelForm):
    class Meta:
        model = Classes
        fields = [
            'matkul',
            'dosen',
            'sks',
            'desc',
            'semester',
            'ruang',
        ]
        widgets = {
            'matkul': forms.TextInput(attrs={'class': 'form-control'}),
            'dosen': forms.TextInput(attrs={'class': 'form-control'}),
            'sks': forms.TextInput(attrs={'class': 'form-control'}),
            'desc': forms.Textarea(attrs={'class': 'form-control'}),
            'semester': forms.TextInput(attrs={'class': 'form-control'}),
            'ruang': forms.TextInput(attrs={'class': 'form-control'}),
        }

classes/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, DeleteView
from .forms import ClassesForm
from .models import Classes
from django.urls import reverse_lazy

# Create your views here.

class ClassesView(ListView):
    model = Classes
    template_name = 'classes/list.html'

class ClassesDetailView(DetailView):
    model = Classes
    template_name = 'classes/detail.html'

class ClassesDeleteView(DeleteView):
    model = Classes
    template_name = 'classes/delete.html'
    success_url = reverse_lazy('classes:list')

def add(request):
    form = ClassesForm(request.POST or None)
    if form.is_valid():
        form.save()
    context = {
        'form': form
    }
    return render(request, 'classes/add.html', context)

home/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'home/index.html')

classes/templates/classes/add.html
{% extends "base.html" %}
{% block content %}

<div class="container text-center content" style="max-width: 600px;">
    <div class="whitespace-2"></div>
    <div class="text-center">
        <h1 class="title-name-2 color-2">Add Subjects</h1>
        <br>
    </div>
    <form method='POST'> {% csrf_token %}
        {{ form.as_p}}
        <input type='submit' value='save' />
    </form>
    <br>
    <a href="/classes/">Show Me The Result</a>
</div>
<div class="whitespace-1"></div>
{% endblock %}

classes/templates/classes/delete.html
{% extends "base.html" %}
{% block content %}
<div class="container text-center content">
    <div class="whitespace-1"></div>
    <h3>Delete: {{ classes.matkul }}</h3>
    <br><br>
    <div class="form-group">
        <form method="POST">
            {% csrf_token %}
            <strong>Are you sure about that?</strong>
            <br><br>
            <button class="btn btn-secondary">Delete Class</button>
        </form>
    </div>
    <a href="/classes/"><h4>No! Take Me Back!</h4></a>
</div>
<div class="whitespace-1"></div>
<div class="whitespace-4"></div>
{% endblock %}

classes/templates/classes/detail.html
{% extends "base.html" %}
{% block content %}
<div class="whitespace-4"></div>
<div class="content container">
    <h1 class="text-center title-name-2 color-2">{{ classes.matkul }}</h1>
    <table class="table table-striped">
        <thead class="thead-dark">
            <tr>
              <th scope="col">#</th>
              <th scope="col"></th>
              <th scope="col">Penjelasan</th>
            </tr>
          </thead>
        <tbody>
          <tr>
            <th scope="row">1</th>
            <td>mata Kuliah</td>
            <td>{{ classes.matkul }}</td>
          </tr>
          <tr>
            <th scope="row">2</th>
            <td>Dosen</td>
            <td>{{ classes.dosen }}</td>
          </tr>
          <tr>
            <th scope="row">3</th>
            <td>Jumlah SKS</td>
            <td>{{ classes.sks }}</td>
          </tr>
         
          <tr>
            <th scope="row">4</th>
            <td>Semester Tahun</td>
            <td>{{ classes.semester }}</td>
          </tr>
          <tr>
            <th scope="row">5</th>
            <td>Ruang Kelas</td>
            <td>{{ classes.ruang }}</td>
          </tr>
          <tr>
            <th scope="row">6</th>
            <td>Deskripsi Mata Kuliah</td>
            <td>{{ classes.desc }}</td>
          </tr>
        </tbody>
      </table>
</div>
<div class="whitespace-1"></div>
{% endblock %}

classes/templates/classes/list.html
{% extends "base.html" %}
{% block content %}
<div>
    <div class="whitespace-4"></div>
    <div class="text-center">
        <h1 class="title-name-2 color-2">These Are the Classes I am Taking</h1>
    </div>
    <div class="whitespace-2"></div>
    <div class="text-center container">

        <table class="table table-striped content">
                <thead class="thead-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Subject</th>
                        <th scope="col">Press X to Remove</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in object_list %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a href="{% url 'classes:classes-detail' item.pk %}">{{ item.matkul }}</a></td>
                        <td>
                            <a href="{% url 'classes:classes-delete' item.pk %}"><h3 style="text-align: center;">X</h3></a>
                        </td>
                    </tr>

                    {% endfor %}
                </tbody>
            </table>
    </div>
</div>
<div class="whitespace-1"></div>

{% endblock %}

home/templates/home/index.html
    {% extends "base.html" %}
                    
                {% block content %}
                <img src="../static/images/JP47.jpg" alt="lukas">
                {% endblock %}
            

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Caveat' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Roboto Slab' rel='stylesheet'>

    <title>Samuel Sharon</title>
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-xl-1 col-lg-2 col-md-2 col-sm-3 d-none d-sm-block px-1 position-fixed fixed-sidebar"
                id="sticky-sidebar">
                <div class="text-center fixed-sidebar-contents">
                    
                    <a class="color-2" href="/">
                        <h1 class="content-2" style="color: orange;">Profile</h1>
                    </a>
                    
                    
                    <a class="color-2" href="/classes/">
                        <h1 class="content-2" style="color: orange;">Classes</h1>
                    </a>
                    <a class="color-2" href="/classes/add">
                        <h1 class="content-2" style="color: orange;">Add Class</h1>
                    </a>
                    <br>
                    
                    
                </div>
            </div>
            <div class="offset-xl-1 offset-lg-2 offset-md-2 offset-sm-3" id="main">

                <nav class="d-block d-sm-none navbar navbar-expand-lg navbar-dark navbar-inverse fixed-top">
                    <a class="navbar-brand" href="#">Tabs</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                      <span class="navbar-toggler-icon"></span>
                    </button>
                  
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                      <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                          <a class="nav-link" href="/">Profile</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link" href="/classes/">Classes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/classes/add">Add Class</a>
                        </li>
                    </div>
                </nav>
                {% block content %}
                {% endblock %}
                <div style="width: 100%; background-color: #000D00;">
                    <p style="color: #000D00;">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptas magnam nobis fugit quis odit aut repudiandae, corporis, iusto repellendus facilis similique pariatur, voluptate veritatis laudantium facere et a accusamus ratione? Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio dolore velit earum necessitatibus ipsum nostrum tenetur vel sed nisi aspernatur nobis, fugiat eius nam pariatur veniam corporis? In, repudiandae ex?</p>
                </div>
            </div>
        </div>
    </div>
    <!-- necessary for the bootstrap navbar -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>

</html>